Fix various compilation bugs
-c src/screens/play_round.c -o out/src/screens/play_round.o

src/screens/play_round.c: In function 'show_standings_brief':

src/screens/play_round.c:68:9: warning: 'count' is used uninitialized in this function [-Wuninitialized]

     u8  top = (count > 10u) ? 10u : count;

         ^~~

D:/Pessoal/Projetos/sgdk170/bin/mkdir.exe -p out/src/screens/

D:/Pessoal/Projetos/sgdk170/bin/gcc.exe  -DSGDK_GCC -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -ID:/Pessoal/Projetos/sgdk170/inc -ID:/Pessoal/Projetos/sgdk170/res -BD:/Pessoal/Projetos/sgdk170/bin -O3 -fuse-linker-plugin -fno-web -fno-gcse -fno-unit-at-a-time -fomit-frame-pointer -flto -MMD -c src/screens/save_load.c -o out/src/screens/save_load.o

D:/Pessoal/Projetos/sgdk170/bin/mkdir.exe -p out/src/screens/

D:/Pessoal/Projetos/sgdk170/bin/gcc.exe  -DSGDK_GCC -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -ID:/Pessoal/Projetos/sgdk170/inc -ID:/Pessoal/Projetos/sgdk170/res -BD:/Pessoal/Projetos/sgdk170/bin -O3 -fuse-linker-plugin -fno-web -fno-gcse -fno-unit-at-a-time -fomit-frame-pointer -flto -MMD -c src/screens/standings.c -o out/src/screens/standings.o

D:/Pessoal/Projetos/sgdk170/bin/mkdir.exe -p out/src/screens/

D:/Pessoal/Projetos/sgdk170/bin/gcc.exe  -DSGDK_GCC -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -ID:/Pessoal/Projetos/sgdk170/inc -ID:/Pessoal/Projetos/sgdk170/res -BD:/Pessoal/Projetos/sgdk170/bin -O3 -fuse-linker-plugin -fno-web -fno-gcse -fno-unit-at-a-time -fomit-frame-pointer -flto -MMD -c src/screens/title.c -o out/src/screens/title.o

D:/Pessoal/Projetos/sgdk170/bin/mkdir.exe -p out/src/screens/

D:/Pessoal/Projetos/sgdk170/bin/gcc.exe  -DSGDK_GCC -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -ID:/Pessoal/Projetos/sgdk170/inc -ID:/Pessoal/Projetos/sgdk170/res -BD:/Pessoal/Projetos/sgdk170/bin -O3 -fuse-linker-plugin -fno-web -fno-gcse -fno-unit-at-a-time -fomit-frame-pointer -flto -MMD -c src/screens/transfers.c -o out/src/screens/transfers.o

echo "out/res/resources.o out/src/main.o out/src/engine/compat.o out/src/engine/font_data.o out/src/engine/input.o out/src/engine/render.o out/src/engine/rng.o out/src/engine/sram_io.o out/src/engine/ui.o out/src/game/cup.o out/src/game/data.o out/src/game/economy.o out/src/game/league.o out/src/game/match.o out/src/game/season.o out/src/game/transfer.o out/src/screens/coaches.o out/src/screens/cup_screen.o out/src/screens/finances.o out/src/screens/main_menu.o out/src/screens/palmares.o out/src/screens/play_round.o out/src/screens/save_load.o out/src/screens/squad.o out/src/screens/stadium.o out/src/screens/standings.o out/src/screens/title.o out/src/screens/transfers.o" > out/cmd_

D:/Pessoal/Projetos/sgdk170/bin/gcc.exe -BD:/Pessoal/Projetos/sgdk170/bin -n -T D:/Pessoal/Projetos/sgdk170/md.ld -nostdlib out/sega.o @out/cmd_ D:/Pessoal/Projetos/sgdk170/lib/libmd.a D:/Pessoal/Projetos/sgdk170/lib/libgcc.a -o out/rom.out -Wl,--gc-sections

src/engine/render.c:10:5: warning: type of 'vsprintf' does not match original declaration [-Wlto-type-mismatch]

 int vsprintf(char *buf, const char *fmt, __builtin_va_list ap);

     ^

D:/apps/SGDK/src/string.c:364:5: note: return value type mismatch

D:/Pessoal/Projetos/sgdk170/inc/types.h:107:24: note: type 'u16' should match type 'int'

 typedef unsigned short u16;

                        ^

D:/apps/SGDK/src/string.c:364:5: note: 'vsprintf' was previously declared here

D:/apps/SGDK/src/string.c:364:5: note: code may be misoptimized unless -fno-strict-aliasing is used

D:/apps/SGDK/src/sys.c:66:12: warning: type of 'main' does not match original declaration [-Wlto-type-mismatch]

src/main.c:18:5: note: type mismatch in parameter 1

 #include "screens/save_load.h"

     ^

src/main.c:18:5: note: type 'int' should match type 'bool'

D:/Pessoal/Projetos/sgdk170/inc/types.h:80:24: note: the incompatible type is defined here

 typedef unsigned short bool;

                        ^

src/main.c:18:5: note: 'main' was previously declared here

 #include "screens/save_load.h"

     ^

src/main.c:18:5: note: code may be misoptimized unless -fno-strict-aliasing is used

C:\Users\HAROLD~1\AppData\Local\Temp\ccfzNRMw.ltrans0.ltrans.o: In function `main.constprop.16':

<artificial>:(.text+0x2e6): undefined reference to `g_goals'

<artificial>:(.text+0x31e): undefined reference to `g_goals'

<artificial>:(.text+0xaee): undefined reference to `g_goals'

<artificial>:(.text+0xb26): undefined reference to `g_goals'

<artificial>:(.text+0x2450): undefined reference to `g_goals'

C:\Users\HAROLD~1\AppData\Local\Temp\ccfzNRMw.ltrans2.ltrans.o:<artificial>:(.text+0x480): more undefined references to `g_goals' follow

make: *** [out/rom.out] Error 1

rm res/resources.rs